### ISSUE TITLE
Viewing 'Your Voting History' displays null fields

### ISSUE THREAD

**Issue by blogscot** [1503491/PollingApp#3]
I created a number of polls to test the Open / Closed / My Polls pages, and deleted a few of them in the process. The 'Your Voting History' now shows empty fields, e.g. line 2-3, 6-7. Do we have a system test for this? @BigpapaKK @1503491 
---

There's no such thing as an old dog - Active
- Finished
- Finished
What day is it? - Active
Who was the best Dr Who? - Active
- Finished
- Finished
Who is the fairest of them all? - Active
What is the best number? - Finished
Should Britain leave the EU? - Finished

**Comment by blogscot** [comment]
I've found the following workaround to filter out empty entries:

votinghistory.php

      <h2>My Voting History</h2>
      <div class="panel-group">
         <div class="row">
           {% for vote in votes if vote.poll.question is not empty %}

**Comment by 1503491** [comment]
We are now correctly deleting the votes when a poll is deleted
