### ISSUE TITLE
Voting history shows wrong information

### ISSUE THREAD

**Issue by blogscot** [1503491/PollingApp#4]
The scenario is a user votes on a poll that is later deleted. The database records that they have voted, but there is no poll in the database, so nothing is displayed.

function getVotedOnPolls() returns 1 instead of 0 because poll_voters still contains information about poll 10 although this has been deleted from the polls table.

# id, user_id, poll_id, option_id, created_at, updated_at
'13', '2', '10', '27', '2016-03-04 19:18:14', '2016-03-04 19:18:14'
'14', '3', '10', '28', '2016-03-04 19:25:35', '2016-03-04 19:25:35'
'15', '1', '10', '27', '2016-03-06 18:47:43', '2016-03-06 18:47:43'

**Comment by 1503491** [comment]
Fixed in previous issue
